/*******************************************************************************
Copyright (C) 2015 OLogN Technologies AG

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License version 2 as
    published by the Free Software Foundation.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*******************************************************************************/

/*******************************************************************************
THIS FILE IS AUTOMATICALLY GENERATED BASED ON DESIRED PLUGIN LIST, SETTINGS
*******************************************************************************/


#include "sa_bus_list.h"
#include "transports/serial/serial.h"

#ifdef SA_PLATFORM_WIRING
hapi_serial_t sa_serial  = {(void*)&Serial, SERIAL_TYPE_HARDWARE};
#elif SA_PLATFORM_MBED
Serial pc_serial(USBTX, USBRX);
hapi_serial_t sa_serial  = {(void*)&pc_serial, SERIAL_TYPE_HARDWARE};
#else
hapi_serial_t sa_serial  = {(void*)0, SERIAL_TYPE_HARDWARE};
#endif

serial_transport_config serial_transport_config_0 = {&sa_serial, 9600};

serial_transport_state serial_transport_state_0 = {0};

extern const sa_transport serial_transport;

const uint8_t SA_BUSES_MAX ZEPTO_PROG_CONSTANT_LOCATION = 1;
const bus_item buses[1] ZEPTO_PROG_CONSTANT_LOCATION =
{
    {
        &serial_transport,
        &serial_transport_config_0,
        &serial_transport_state_0
    }
};
