/*******************************************************************************
Copyright (C) 2015 OLogN Technologies AG

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License version 2 as
    published by the Free Software Foundation.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*******************************************************************************/

/*******************************************************************************
THIS FILE IS AUTOMATICALLY GENERATED BASED ON DESIRED PLUGIN LIST, SETTINGS
*******************************************************************************/


#include "sa_transports_list.h"
#include "transports/serial/serial.h"

#ifdef SA_PLATFORM_WIRING
serial_transport_config serial_transport_config_0 = {0, 1, 9600};
hapi_serial_t sa_serial  = {(void*)&Serial, SERIAL_TYPE_HARDWARE};
#define SERIAL_PTR &sa_serial
#elif SA_PLATFORM_MBED
serial_transport_config serial_transport_config_0 = {USBRX, USBTX, 9600};
Serial pc_serial((PinName)serial_transport_config_0.tx, (PinName)serial_transport_config_0.rx);
hapi_serial_t sa_serial  = {(void*)&pc_serial, SERIAL_TYPE_HARDWARE};
#define SERIAL_PTR &sa_serial
#else
serial_transport_config serial_transport_config_0 = {0, 1, 9600};
#define SERIAL_PTR 0
#endif

serial_transport_state serial_transport_state_0 =
{
    SERIAL_PTR
};

extern const sa_transport serial_transport;

const uint8_t SA_TRANSPORTS_MAX ZEPTO_PROG_CONSTANT_LOCATION = 1;
const transport_item transports[1] ZEPTO_PROG_CONSTANT_LOCATION =
{
    {
        &serial_transport,
        &serial_transport_config_0,
        &serial_transport_state_0
    }
};
