/*******************************************************************************
Copyright (C) 2015 OLogN Technologies AG

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License version 2 as
    published by the Free Software Foundation.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*******************************************************************************/

/*******************************************************************************
THIS FILE IS AUTOMATICALLY GENERATED BASED ON DESIRED PLUGIN LIST, SETTINGS
*******************************************************************************/


#include "sa_transports_list.h"

#include "transports/serial/serial.h"

serial_transport_config serial_transport_config_0 = {
    .rx=0,
    .tx=1,
    .baudrate=9600
};

serial_transport_state serial_transport_state_0 =
{
    .serial_obj=(void*)&Serial
};

extern const sa_transport serial_transport;

const uint8_t SA_TRANSPORTS_MAX ZEPTO_PROG_CONSTANT_LOCATION = 1;
const transport_item transports[1] ZEPTO_PROG_CONSTANT_LOCATION =
{
    {
        &serial_transport,
        &serial_transport_config_0,
        &serial_transport_state_0
    }
};
